# Generated by Django 4.0.5 on 2022-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
