# Generated by Django 4.0.5 on 2022-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customer_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
